name: flutter_datetime_picker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: 3.24.0

dependencies:
  flutter:
    sdk: flutter
  flutter_datetime_picker_plus: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_gen_runner: 5.6.0
  build_runner: 2.4.12

flutter:
  uses-material-design: true

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    rive: false
    lottie: false

  assets:
    exclude:
      - assets/google_fonts
